"""
Generate PDF reports for road damages using ReportLab.
"""

from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors


def generate_pdf_report(damages, filepath):
    """
    Generate a styled PDF report for road damages.
    """
    # Create the document template
    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )
    
    styles = getSampleStyleSheet()
    
    # Custom premium styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0288d1'),
        spaceAfter=15
    )
    
    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=16,
        textColor=colors.HexColor('#333333'),
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#555555')
    )

    header_text_style = ParagraphStyle(
        'HeaderStyle',
        parent=body_style,
        textColor=colors.white,
        fontName='Helvetica-Bold'
    )
    
    story = []
    
    # Title & Header
    story.append(Paragraph("Road Damage Inspection Report", title_style))
    story.append(Paragraph("Generated by: AI Road Damage Detection and Repair Prioritization System", body_style))
    story.append(Spacer(1, 15))
    
    # Summary Section
    story.append(Paragraph("Executive Summary", section_style))
    
    total = len(damages)
    critical = sum(1 for r in damages if r["severity"] == "Critical")
    high = sum(1 for r in damages if r["severity"] == "High")
    medium = sum(1 for r in damages if r["severity"] == "Medium")
    low = sum(1 for r in damages if r["severity"] == "Low")
    
    summary_text = (
        f"This report contains details of <b>{total}</b> detected road damage incidents. "
        f"A severity breakdown reveals <b>{critical}</b> critical issues, <b>{high}</b> high severity issues, "
        f"<b>{medium}</b> medium severity issues, and <b>{low}</b> low severity issues. "
        "Critical and high-severity damages require immediate repair dispatch."
    )
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 15))
    
    # Summary Table
    summary_data = [
        [Paragraph("Severity", header_text_style), Paragraph("Count", header_text_style), Paragraph("Priority Level", header_text_style)],
        [Paragraph("Critical", body_style), Paragraph(str(critical), body_style), Paragraph("<font color='red'><b>Urgent (Immediate Dispatch)</b></font>", body_style)],
        [Paragraph("High", body_style), Paragraph(str(high), body_style), Paragraph("<font color='orange'><b>High Priority</b></font>", body_style)],
        [Paragraph("Medium", body_style), Paragraph(str(medium), body_style), Paragraph("Scheduled Maintenance", body_style)],
        [Paragraph("Low", body_style), Paragraph(str(low), body_style), Paragraph("Routine Monitoring", body_style)]
    ]
    
    summary_table = Table(summary_data, colWidths=[100, 80, 200])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0288d1')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#dddddd')),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 20))
    
    # Detailed Table Section
    story.append(Paragraph("Detailed Damage Records", section_style))
    
    # Table headers
    detailed_data = [[
        Paragraph("ID", header_text_style),
        Paragraph("Type", header_text_style),
        Paragraph("Severity", header_text_style),
        Paragraph("Confidence", header_text_style),
        Paragraph("Coordinates", header_text_style),
        Paragraph("Logged At", header_text_style)
    ]]
    
    for r in damages:
        # Style severity text
        sev = r['severity']
        if sev == "Critical":
            sev_p = Paragraph("<font color='red'><b>Critical</b></font>", body_style)
        elif sev == "High":
            sev_p = Paragraph("<font color='orange'>High</font>", body_style)
        elif sev == "Medium":
            sev_p = Paragraph("<font color='#d4af37'>Medium</font>", body_style)
        else:
            sev_p = Paragraph("<font color='green'>Low</font>", body_style)
            
        detailed_data.append([
            Paragraph(str(r["id"]), body_style),
            Paragraph(r["damage_type"], body_style),
            sev_p,
            Paragraph(f"{r['confidence'] * 100:.1f}%", body_style),
            Paragraph(f"{r['latitude']:.4f}, {r['longitude']:.4f}", body_style),
            Paragraph(r["timestamp"], body_style)
        ])
        
    detailed_table = Table(detailed_data, colWidths=[30, 100, 60, 60, 120, 120])
    detailed_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0288d1')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cccccc')),
    ]))
    
    story.append(detailed_table)
    
    # Build document
    doc.build(story)
    print(f"PDF report written to {filepath}")
